@echo off

setlocal
set HASUNE_BASE=C:\data\programs\hasune.rs
set COUNT_FREQUENCIES_BASE=%HASUNE_BASE%\utility\word_frequency\count_frequencies
set COUNT_FREQUENCIES_PY=%COUNT_FREQUENCIES_BASE%\hasune.count_frequencies.py
set MERGE_FREQUENCIES_PY=%COUNT_FREQUENCIES_BASE%\hasune.merge_frequencies.py
set ADJUST_FREQUENCIES_BASE=%HASUNE_BASE%\utility\word_frequency\adjust_frequencies
set BLEND_FREQUENCIES_PY=%ADJUST_FREQUENCIES_BASE%\hasune.blend_frequencies.py
set AMPLIFY_FREQUENCIES_PY=%ADJUST_FREQUENCIES_BASE%\hasune.amplify_frequencies.py

set WIKIPEDIA_MORPHEMES_DIR=..\02_corpus\wikipedia\hasune_pos
set WIKIPEDIA_FREQUENCIES_DIR=wikipedia_frequencies
set INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR=intermediate_wikipedia_frequencies
set MERGED_WIKIPEDIA_FREQUENCIES_DIR=merged_wikipedia_frequencies
set AOZORA_MORPHEMES_DIR=..\02_corpus\aozora\hasune_pos
set AOZORA_FREQUENCIES_DIR=aozora_frequencies
set INTERMEDIATE_AOZORA_FREQUENCIES_DIR=intermediate_aozora_frequencies
set MERGED_AOZORA_FREQUENCIES_DIR=merged_aozora_frequencies
rem WIKIPEDIA=5.97GB, AOZORA=292MB
set WIKIPEDIA_RATIO=1
set AOZORA_RATIO=20
set BLENDED_FREQUENCIES_DIR=blended_frequencies
set FREQ_MAGNIFICATIONS_TXT=%ADJUST_FREQUENCIES_BASE%\data\freq_magnifications.txt
set AMPLIFIED_FREQUENCIES_DIR=amplified_frequencies

rem 21min
time /t
echo python %COUNT_FREQUENCIES_PY% %WIKIPEDIA_MORPHEMES_DIR% %WIKIPEDIA_FREQUENCIES_DIR%
python %COUNT_FREQUENCIES_PY% %WIKIPEDIA_MORPHEMES_DIR% %WIKIPEDIA_FREQUENCIES_DIR% || exit /b 1

rem <1min
time /t
echo python %COUNT_FREQUENCIES_PY% %AOZORA_MORPHEMES_DIR% %AOZORA_FREQUENCIES_DIR%
python %COUNT_FREQUENCIES_PY% %AOZORA_MORPHEMES_DIR% %AOZORA_FREQUENCIES_DIR% || exit /b 1

rem 21min
time /t
rmdir /s /q %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR%
mkdir %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR%
echo python %MERGE_FREQUENCIES_PY% %WIKIPEDIA_FREQUENCIES_DIR% pos_bi.  %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% %WIKIPEDIA_FREQUENCIES_DIR% pos_bi.  %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% || exit /b 1
echo python %MERGE_FREQUENCIES_PY% %WIKIPEDIA_FREQUENCIES_DIR% pos_uni. %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% %WIKIPEDIA_FREQUENCIES_DIR% pos_uni. %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% || exit /b 1
echo python %MERGE_FREQUENCIES_PY% %WIKIPEDIA_FREQUENCIES_DIR% word.    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% %WIKIPEDIA_FREQUENCIES_DIR% word.    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% || exit /b 1
rmdir /s /q %MERGED_WIKIPEDIA_FREQUENCIES_DIR%
mkdir %MERGED_WIKIPEDIA_FREQUENCIES_DIR%
echo python %MERGE_FREQUENCIES_PY% %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% pos_bi.  %MERGED_WIKIPEDIA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% pos_bi.  %MERGED_WIKIPEDIA_FREQUENCIES_DIR% || exit /b 1
echo python %MERGE_FREQUENCIES_PY% %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% pos_uni. %MERGED_WIKIPEDIA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% pos_uni. %MERGED_WIKIPEDIA_FREQUENCIES_DIR% || exit /b 1
echo python %MERGE_FREQUENCIES_PY% %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% word.    %MERGED_WIKIPEDIA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% word.    %MERGED_WIKIPEDIA_FREQUENCIES_DIR% || exit /b 1
rename %MERGED_WIKIPEDIA_FREQUENCIES_DIR%\*.%INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% *.merged_frequencies

rem <1min
time /t
rmdir /s /q %INTERMEDIATE_AOZORA_FREQUENCIES_DIR%
mkdir %INTERMEDIATE_AOZORA_FREQUENCIES_DIR%
echo python %MERGE_FREQUENCIES_PY% %AOZORA_FREQUENCIES_DIR% pos_bi.  %INTERMEDIATE_AOZORA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% %AOZORA_FREQUENCIES_DIR% pos_bi.  %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% || exit /b 1
echo python %MERGE_FREQUENCIES_PY% %AOZORA_FREQUENCIES_DIR% pos_uni. %INTERMEDIATE_AOZORA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% %AOZORA_FREQUENCIES_DIR% pos_uni. %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% || exit /b 1
echo python %MERGE_FREQUENCIES_PY% %AOZORA_FREQUENCIES_DIR% word.    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% %AOZORA_FREQUENCIES_DIR% word.    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% || exit /b 1
rmdir /s /q %MERGED_AOZORA_FREQUENCIES_DIR%
mkdir %MERGED_AOZORA_FREQUENCIES_DIR%
echo python %MERGE_FREQUENCIES_PY% %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% pos_bi.  %MERGED_AOZORA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% pos_bi.  %MERGED_AOZORA_FREQUENCIES_DIR% || exit /b 1
echo python %MERGE_FREQUENCIES_PY% %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% pos_uni. %MERGED_AOZORA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% pos_uni. %MERGED_AOZORA_FREQUENCIES_DIR% || exit /b 1
echo python %MERGE_FREQUENCIES_PY% %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% word.    %MERGED_AOZORA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% word.    %MERGED_AOZORA_FREQUENCIES_DIR% || exit /b 1
rename %MERGED_AOZORA_FREQUENCIES_DIR%\*.%INTERMEDIATE_AOZORA_FREQUENCIES_DIR% *.merged_frequencies

rem <1min
time /t
rmdir /s /q %BLENDED_FREQUENCIES_DIR%
mkdir %BLENDED_FREQUENCIES_DIR%
echo python %BLEND_FREQUENCIES_PY% ^
    %MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
    %WIKIPEDIA_RATIO% ^
    %MERGED_AOZORA_FREQUENCIES_DIR% ^
    %AOZORA_RATIO% ^
    %BLENDED_FREQUENCIES_DIR%
python %BLEND_FREQUENCIES_PY% ^
    %MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
    %WIKIPEDIA_RATIO% ^
    %MERGED_AOZORA_FREQUENCIES_DIR% ^
    %AOZORA_RATIO% ^
    %BLENDED_FREQUENCIES_DIR% || exit /b

rem <1min
time /t
rmdir /s /q %AMPLIFIED_FREQUENCIES_DIR%
mkdir %AMPLIFIED_FREQUENCIES_DIR%
echo python %AMPLIFY_FREQUENCIES_PY% %FREQ_MAGNIFICATIONS_TXT% %BLENDED_FREQUENCIES_DIR% %AMPLIFIED_FREQUENCIES_DIR%
python %AMPLIFY_FREQUENCIES_PY% %FREQ_MAGNIFICATIONS_TXT% %BLENDED_FREQUENCIES_DIR% %AMPLIFIED_FREQUENCIES_DIR% || exit /b

time /t
echo FINISHED!
exit /b 0
