@echo off

setlocal
set HASUNE_BASE=C:\data\programs\hasune.rs
set ADJUST_FREQUENCIES_BASE=%HASUNE_BASE%\utility\word_frequency\adjust_frequencies
set BLEND_FREQUENCIES_PY=%ADJUST_FREQUENCIES_BASE%\hasune.blend_frequencies.py
set AMPLIFY_FREQUENCIES_PY=%ADJUST_FREQUENCIES_BASE%\hasune.amplify_frequencies.py
set MAKE_DICT_CONTENT_BASE=%HASUNE_BASE%\utility\dictionary\make_dict_content
set ASSIGN_UNIGRAM_COSTS_PY=%MAKE_DICT_CONTENT_BASE%\hasune.assign_unigram_costs.py
set ASSIGN_BIGRAM_COSTS_PY=%MAKE_DICT_CONTENT_BASE%\hasune.assign_bigram_costs.py

set UNIDIC_MERGED_WIKIPEDIA_FREQUENCIES_DIR=..\03_word_frequency_1\merged_wikipedia_frequencies
set UNIDIC_MERGED_AOZORA_FREQUENCIES_DIR=..\03_word_frequency_1\merged_aozora_frequencies
set COMPOUND_WORD_MERGED_WIKIPEDIA_FREQUENCIES_DIR=..\04_cooccurrence\wikipedia_compound_words
set COMPOUND_WORD_MERGED_AOZORA_FREQUENCIES_DIR=..\04_cooccurrence\aozora_compound_words
rem WIKIPEDIA=5.97GB, AOZORA=292MB
set WIKIPEDIA_RATIO=1
set AOZORA_RATIO=20
set UNIDIC_BLENDED_FREQUENCIES_DIR=unidic_blended_frequencies
set COMPOUND_WORD_BLENDED_FREQUENCIES_DIR=compound_word_blended_frequencies
set BLENDED_FREQUENCIES_DIR=blended_frequencies
set FREQ_MAGNIFICATIONS_TXT=%ADJUST_FREQUENCIES_BASE%\data\freq_magnifications.txt
set AMPLIFIED_FREQUENCIES_DIR=amplified_frequencies
set DICT_CONTENT_NAME=main
set DICT_CONTENT_DIR=..\05_dictionary_content_2\dictionary_content
set DICT_CONTENT_ASSIGNED_DIR=dictionary_content
set WORD_UNICOST_LIST_COST_UNASSIGNED=%DICT_CONTENT_DIR%\%DICT_CONTENT_NAME%.word_unicost_list
set WORD_UNIGRAM_LIST_COST_ASSIGNED=%DICT_CONTENT_ASSIGNED_DIR%\%DICT_CONTENT_NAME%.word_unicost_list.cost_assigned
set POS_BIGRAM_LIST_COST_UNASSIGNED=%DICT_CONTENT_DIR%\%DICT_CONTENT_NAME%.pos_bicost_list
set POS_BIGRAM_LIST_COST_ASSIGNED=%DICT_CONTENT_ASSIGNED_DIR%\%DICT_CONTENT_NAME%.pos_bicost_list.cost_assigned
set RECORD_LIST=%DICT_CONTENT_DIR%\%DICT_CONTENT_NAME%.record_list
set WORD_FREQUENCIES=%AMPLIFIED_FREQUENCIES_DIR%\word.merged_frequencies
set POS_UNIGRAM_FREQUENCIES=%AMPLIFIED_FREQUENCIES_DIR%\pos_uni.merged_frequencies
set POS_BIGRAM_FREQUENCIES=%AMPLIFIED_FREQUENCIES_DIR%\pos_bi.merged_frequencies


@REM rem <1min
@REM time /t
@REM rmdir /s /q %UNIDIC_BLENDED_FREQUENCIES_DIR%
@REM mkdir %UNIDIC_BLENDED_FREQUENCIES_DIR%
@REM echo python %BLEND_FREQUENCIES_PY% ^
@REM     %UNIDIC_MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
@REM     %WIKIPEDIA_RATIO% ^
@REM     %UNIDIC_MERGED_AOZORA_FREQUENCIES_DIR% ^
@REM     %AOZORA_RATIO% ^
@REM     %UNIDIC_BLENDED_FREQUENCIES_DIR%
@REM python %BLEND_FREQUENCIES_PY% ^
@REM     %UNIDIC_MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
@REM     %WIKIPEDIA_RATIO% ^
@REM     %UNIDIC_MERGED_AOZORA_FREQUENCIES_DIR% ^
@REM     %AOZORA_RATIO% ^
@REM     %UNIDIC_BLENDED_FREQUENCIES_DIR% ^
@REM     || exit /b

@REM rem <1min
@REM time /t
@REM rmdir /s /q %COMPOUND_WORD_BLENDED_FREQUENCIES_DIR%
@REM mkdir %COMPOUND_WORD_BLENDED_FREQUENCIES_DIR%
@REM echo python %BLEND_FREQUENCIES_PY% ^
@REM     %COMPOUND_WORD_MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
@REM     %WIKIPEDIA_RATIO% ^
@REM     %COMPOUND_WORD_MERGED_AOZORA_FREQUENCIES_DIR% ^
@REM     %AOZORA_RATIO% ^
@REM     %COMPOUND_WORD_BLENDED_FREQUENCIES_DIR%
@REM python %BLEND_FREQUENCIES_PY% ^
@REM     %COMPOUND_WORD_MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
@REM     %WIKIPEDIA_RATIO% ^
@REM     %COMPOUND_WORD_MERGED_AOZORA_FREQUENCIES_DIR% ^
@REM     %AOZORA_RATIO% ^
@REM     %COMPOUND_WORD_BLENDED_FREQUENCIES_DIR% ^
@REM     || exit /b

@REM rem <1min
@REM time /t
@REM rmdir /s /q %BLENDED_FREQUENCIES_DIR%
@REM mkdir %BLENDED_FREQUENCIES_DIR%
@REM echo python %BLEND_FREQUENCIES_PY% ^
@REM     %UNIDIC_BLENDED_FREQUENCIES_DIR% ^
@REM     1 ^
@REM     %COMPOUND_WORD_BLENDED_FREQUENCIES_DIR% ^
@REM     1 ^
@REM     %BLENDED_FREQUENCIES_DIR%
@REM python %BLEND_FREQUENCIES_PY% ^
@REM     %UNIDIC_BLENDED_FREQUENCIES_DIR% ^
@REM     1 ^
@REM     %COMPOUND_WORD_BLENDED_FREQUENCIES_DIR% ^
@REM     1 ^
@REM     %BLENDED_FREQUENCIES_DIR% ^
@REM     || exit /b

@REM em <1min
@REM time /t
@REM rmdir /s /q %AMPLIFIED_FREQUENCIES_DIR%
@REM mkdir %AMPLIFIED_FREQUENCIES_DIR%
@REM echo python %AMPLIFY_FREQUENCIES_PY% ^
@REM     %FREQ_MAGNIFICATIONS_TXT% ^
@REM     %BLENDED_FREQUENCIES_DIR% ^
@REM     %AMPLIFIED_FREQUENCIES_DIR%
@REM python %AMPLIFY_FREQUENCIES_PY% ^
@REM     %FREQ_MAGNIFICATIONS_TXT% ^
@REM     %BLENDED_FREQUENCIES_DIR% ^
@REM     %AMPLIFIED_FREQUENCIES_DIR% ^
@REM     || exit /b

rem 21min
time /t
rmdir /s /q %DICT_CONTENT_ASSIGNED_DIR%
mkdir %DICT_CONTENT_ASSIGNED_DIR%
echo python %ASSIGN_UNIGRAM_COSTS_PY% ^
    %WORD_UNICOST_LIST_COST_UNASSIGNED% ^
    %RECORD_LIST% ^
    %WORD_FREQUENCIES% ^
    %POS_UNIGRAM_FREQUENCIES% ^
    %WORD_UNIGRAM_LIST_COST_ASSIGNED%
python %ASSIGN_UNIGRAM_COSTS_PY% ^
    %WORD_UNICOST_LIST_COST_UNASSIGNED% ^
    %RECORD_LIST% ^
    %WORD_FREQUENCIES% ^
    %POS_UNIGRAM_FREQUENCIES% ^
    %WORD_UNIGRAM_LIST_COST_ASSIGNED% ^
    || exit /b 1

rem <1min
time /t
echo python %ASSIGN_BIGRAM_COSTS_PY% ^
    %POS_BIGRAM_LIST_COST_UNASSIGNED% ^
    %POS_BIGRAM_FREQUENCIES% ^
    %POS_BIGRAM_LIST_COST_ASSIGNED%
python %ASSIGN_BIGRAM_COSTS_PY% ^
    %POS_BIGRAM_LIST_COST_UNASSIGNED% ^
    %POS_BIGRAM_FREQUENCIES% ^
    %POS_BIGRAM_LIST_COST_ASSIGNED% ^
    || exit /b 1

time /t
echo FINISHED!
exit /b 0
