@echo off

setlocal
set HASUNE_BASE=C:\data\programs\hasune.rs
set ADJUST_FREQUENCIES_BASE=%HASUNE_BASE%\utility\word_frequency\adjust_frequencies
set BLEND_FREQUENCIES_PY=%ADJUST_FREQUENCIES_BASE%\hasune.blend_frequencies.py
set AMPLIFY_FREQUENCIES_PY=%ADJUST_FREQUENCIES_BASE%\hasune.amplify_frequencies.py

set UNIDIC_MERGED_WIKIPEDIA_FREQUENCIES_DIR=..\03_word_frequency_1\merged_wikipedia_frequencies
set UNIDIC_MERGED_AOZORA_FREQUENCIES_DIR=..\03_word_frequency_1\merged_aozora_frequencies
set COMPOUND_WORD_MERGED_WIKIPEDIA_FREQUENCIES_DIR=..\04_cooccurrence\wikipedia_compound_words
set COMPOUND_WORD_MERGED_AOZORA_FREQUENCIES_DIR=..\04_cooccurrence\aozora_compound_words
rem WIKIPEDIA=5.97GB, AOZORA=292MB
set WIKIPEDIA_RATIO=1
set AOZORA_RATIO=20
set UNIDIC_BLENDED_FREQUENCIES_DIR=unidic_blended_frequencies
set COMPOUND_WORD_BLENDED_FREQUENCIES_DIR=compound_word_blended_frequencies
set BLENDED_FREQUENCIES_DIR=blended_frequencies
set FREQ_MAGNIFICATIONS_TXT=%ADJUST_FREQUENCIES_BASE%\data\freq_magnifications.txt
set AMPLIFIED_FREQUENCIES_DIR=amplified_frequencies

rem <1min
time /t
rmdir /s /q %UNIDIC_BLENDED_FREQUENCIES_DIR%
mkdir %UNIDIC_BLENDED_FREQUENCIES_DIR%
echo python %BLEND_FREQUENCIES_PY% ^
    %UNIDIC_MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
    %WIKIPEDIA_RATIO% ^
    %UNIDIC_MERGED_AOZORA_FREQUENCIES_DIR% ^
    %AOZORA_RATIO% ^
    %UNIDIC_BLENDED_FREQUENCIES_DIR%
python %BLEND_FREQUENCIES_PY% ^
    %UNIDIC_MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
    %WIKIPEDIA_RATIO% ^
    %UNIDIC_MERGED_AOZORA_FREQUENCIES_DIR% ^
    %AOZORA_RATIO% ^
    %UNIDIC_BLENDED_FREQUENCIES_DIR% ^
    || exit /b

rem <1min
time /t
rmdir /s /q %COMPOUND_WORD_BLENDED_FREQUENCIES_DIR%
mkdir %COMPOUND_WORD_BLENDED_FREQUENCIES_DIR%
echo python %BLEND_FREQUENCIES_PY% ^
    %COMPOUND_WORD_MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
    %WIKIPEDIA_RATIO% ^
    %COMPOUND_WORD_MERGED_AOZORA_FREQUENCIES_DIR% ^
    %AOZORA_RATIO% ^
    %COMPOUND_WORD_BLENDED_FREQUENCIES_DIR%
python %BLEND_FREQUENCIES_PY% ^
    %COMPOUND_WORD_MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
    %WIKIPEDIA_RATIO% ^
    %COMPOUND_WORD_MERGED_AOZORA_FREQUENCIES_DIR% ^
    %AOZORA_RATIO% ^
    %COMPOUND_WORD_BLENDED_FREQUENCIES_DIR% ^
    || exit /b

rem <1min
time /t
rmdir /s /q %BLENDED_FREQUENCIES_DIR%
mkdir %BLENDED_FREQUENCIES_DIR%
echo python %BLEND_FREQUENCIES_PY% ^
    %UNIDIC_BLENDED_FREQUENCIES_DIR% ^
    1 ^
    %COMPOUND_WORD_BLENDED_FREQUENCIES_DIR% ^
    1 ^
    %BLENDED_FREQUENCIES_DIR%
python %BLEND_FREQUENCIES_PY% ^
    %UNIDIC_BLENDED_FREQUENCIES_DIR% ^
    1 ^
    %COMPOUND_WORD_BLENDED_FREQUENCIES_DIR% ^
    1 ^
    %BLENDED_FREQUENCIES_DIR% ^
    || exit /b

em <1min
time /t
rmdir /s /q %AMPLIFIED_FREQUENCIES_DIR%
mkdir %AMPLIFIED_FREQUENCIES_DIR%
echo python %AMPLIFY_FREQUENCIES_PY% ^
    %FREQ_MAGNIFICATIONS_TXT% ^
    %BLENDED_FREQUENCIES_DIR% ^
    %AMPLIFIED_FREQUENCIES_DIR%
python %AMPLIFY_FREQUENCIES_PY% ^
    %FREQ_MAGNIFICATIONS_TXT% ^
    %BLENDED_FREQUENCIES_DIR% ^
    %AMPLIFIED_FREQUENCIES_DIR% ^
    || exit /b

time /t
echo FINISHED!
exit /b 0
