@echo off

setlocal
set HASUNE_BASE=C:\data\programs\hasune.rs
set COUNT_FREQUENCIES_BASE=%HASUNE_BASE%\utility\word_frequency\count_frequencies
set COUNT_FREQUENCIES_PY=%COUNT_FREQUENCIES_BASE%\hasune.count_frequencies.py
set MERGE_FREQUENCIES_PY=%COUNT_FREQUENCIES_BASE%\hasune.merge_frequencies.py

set WIKIPEDIA_MORPHEMES_DIR=..\02_corpus\wikipedia\hasune_pos
set WIKIPEDIA_FREQUENCIES_DIR=wikipedia_frequencies
set INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR=intermediate_wikipedia_frequencies
set MERGED_WIKIPEDIA_FREQUENCIES_DIR=merged_wikipedia_frequencies
set AOZORA_MORPHEMES_DIR=..\02_corpus\aozora\hasune_pos
set AOZORA_FREQUENCIES_DIR=aozora_frequencies
set INTERMEDIATE_AOZORA_FREQUENCIES_DIR=intermediate_aozora_frequencies
set MERGED_AOZORA_FREQUENCIES_DIR=merged_aozora_frequencies

rem 21min
time /t
echo python %COUNT_FREQUENCIES_PY% ^
    %WIKIPEDIA_MORPHEMES_DIR% ^
    %WIKIPEDIA_FREQUENCIES_DIR%
python %COUNT_FREQUENCIES_PY% ^
    %WIKIPEDIA_MORPHEMES_DIR% ^
    %WIKIPEDIA_FREQUENCIES_DIR% ^
    || exit /b 1

rem <1min
time /t
echo python %COUNT_FREQUENCIES_PY% ^
    %AOZORA_MORPHEMES_DIR% ^
    %AOZORA_FREQUENCIES_DIR%
python %COUNT_FREQUENCIES_PY% ^
    %AOZORA_MORPHEMES_DIR% ^
    %AOZORA_FREQUENCIES_DIR% ^
    || exit /b 1

rem 21min
time /t
rmdir /s /q %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR%
mkdir %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR%
echo python %MERGE_FREQUENCIES_PY% ^
    %WIKIPEDIA_FREQUENCIES_DIR% ^
    pos_bi. ^
    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% ^
    %WIKIPEDIA_FREQUENCIES_DIR% ^
    pos_bi. ^
    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% ^
    || exit /b 1
echo python %MERGE_FREQUENCIES_PY% ^
    %WIKIPEDIA_FREQUENCIES_DIR% ^
    pos_uni. ^
    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% ^
    %WIKIPEDIA_FREQUENCIES_DIR% ^
    pos_uni. ^
    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% ^
    || exit /b 1
echo python %MERGE_FREQUENCIES_PY% ^
    %WIKIPEDIA_FREQUENCIES_DIR% ^
    word. ^
    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% ^
    %WIKIPEDIA_FREQUENCIES_DIR% ^
    word. ^
    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% ^
    || exit /b 1
rmdir /s /q %MERGED_WIKIPEDIA_FREQUENCIES_DIR%
mkdir %MERGED_WIKIPEDIA_FREQUENCIES_DIR%
echo python %MERGE_FREQUENCIES_PY% ^
    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% ^
    pos_bi. ^
    %MERGED_WIKIPEDIA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% ^
    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% ^
    pos_bi. ^
    %MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
    || exit /b 1
echo python %MERGE_FREQUENCIES_PY% ^
    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% ^
    pos_uni. ^
    %MERGED_WIKIPEDIA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% ^
    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% ^
    pos_uni. ^
    %MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
    || exit /b 1
echo python %MERGE_FREQUENCIES_PY% ^
    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% ^
    word. ^
    %MERGED_WIKIPEDIA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% ^
    %INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% ^
    word. ^
    %MERGED_WIKIPEDIA_FREQUENCIES_DIR% ^
    || exit /b 1
rename ^
    %MERGED_WIKIPEDIA_FREQUENCIES_DIR%\*.%INTERMEDIATE_WIKIPEDIA_FREQUENCIES_DIR% ^
    *.merged_frequencies

rem <1min
time /t
rmdir /s /q %INTERMEDIATE_AOZORA_FREQUENCIES_DIR%
mkdir %INTERMEDIATE_AOZORA_FREQUENCIES_DIR%
echo python %MERGE_FREQUENCIES_PY% ^
    %AOZORA_FREQUENCIES_DIR% pos_bi. ^
    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% ^
    %AOZORA_FREQUENCIES_DIR% pos_bi. ^
    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% ^
    || exit /b 1
echo python %MERGE_FREQUENCIES_PY% ^
    %AOZORA_FREQUENCIES_DIR% ^
    pos_uni. ^
    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% ^
    %AOZORA_FREQUENCIES_DIR% ^
    pos_uni. ^
    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% ^
    || exit /b 1
echo python %MERGE_FREQUENCIES_PY% ^
    %AOZORA_FREQUENCIES_DIR% ^
    word. ^
    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% ^
    %AOZORA_FREQUENCIES_DIR% ^
    word. ^
    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% ^
    || exit /b 1
rmdir /s /q %MERGED_AOZORA_FREQUENCIES_DIR%
mkdir %MERGED_AOZORA_FREQUENCIES_DIR%
echo python %MERGE_FREQUENCIES_PY% ^
    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% ^
    pos_bi. ^
    %MERGED_AOZORA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% ^
    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% ^
    pos_bi. ^
    %MERGED_AOZORA_FREQUENCIES_DIR% ^
    || exit /b 1
echo python %MERGE_FREQUENCIES_PY% ^
    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% ^
    pos_uni. ^
    %MERGED_AOZORA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% ^
    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% ^
    pos_uni. ^
    %MERGED_AOZORA_FREQUENCIES_DIR% ^
    || exit /b 1
echo python %MERGE_FREQUENCIES_PY% ^
    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% ^
    word. ^
    %MERGED_AOZORA_FREQUENCIES_DIR%
python %MERGE_FREQUENCIES_PY% ^
    %INTERMEDIATE_AOZORA_FREQUENCIES_DIR% ^
    word. ^
    %MERGED_AOZORA_FREQUENCIES_DIR% ^
    || exit /b 1
rename ^
    %MERGED_AOZORA_FREQUENCIES_DIR%\*.%INTERMEDIATE_AOZORA_FREQUENCIES_DIR% ^
    *.merged_frequencies

time /t
echo FINISHED!
exit /b 0
